config/routes.rb
Rails.application.routes.draw do
 root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}
  belongs_to :ingredient
  belongs_to :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, except: [:destroy]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.wynnlasvegas.com/-/media/images/wynn-las-vegas/dining/bars-and-lounges/tower-suite-bar/1014_tower_suite_bar_lounge_view_barbara_kraft.ashx?la=en&w=1920&hash=BEDE38121E0AF350CF5B0C18DFD9D103);">
  <div class="container">
    <h1>The Velvet Room</h1>
    <p>Welcome to The Velvet Room loves. Do stay for a drink or two will you?</p>
    <%= link_to "Add a Cocktail", new_cocktail_path, class: "btn btn-gradient" %>
  </div>
</div>

<div class="title">
  <h1>Cocktails</h1>
</div>

<% if @cocktails.empty?%>
    <h2>No Cocktails listed yet. Add some!</h2>
  <% else %>
  <div class="main-container">
    <div class="cards">
      <% @cocktails.each do |cocktail| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cloudinary_url(cocktail.photo&.key) if cocktail.photo.attached? %>)">
          <%= link_to cocktail.name, cocktail_path(cocktail)  %>
        </div>
      <% end %>
      </div>
    </div>  
<% end %>

app/views/cocktails/new.html.erb
<h2>Add a cocktail:</h2>
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name, placeholder: "Add a name" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add", class: "btn btn-gradient" %>
    <% end %>
    

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cloudinary_url(@cocktail.photo&.key) if @cocktail.photo.attached? %>);">
  <div class="container">
<h1><%= @cocktail.name %></h1>
  </div>
</div>



<% if @cocktail.doses.present? %>
  <% @cocktail.doses.each do |dose| %>
    <h1><%= dose.ingredient.name %>: <%= dose.description %> 
     <%= link_to dose_path(dose), class: "btn btn-gradient", method: :delete, data: { confirm: "Are you sure?"} do %>
                      <h2>Delete ingredient</h2>
      <% end %> </h1>
    <hr>
  <% end %>
    <%= link_to "Add some more ingredients!",  new_cocktail_dose_path(@cocktail), class: "btn btn-gradient" %>
<% else %>
  <h2>No ingredients listed, add some!</h2>
  <%= link_to "Add some ingredients!",  new_cocktail_dose_path(@cocktail), class: "btn btn-gradient" %>
<% end %>
<%= link_to "Return to Cocktails list", cocktails_path, class: "btn btn-gradient" %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/new.html.erb
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient, as: :select %>
          <%= f.input :description, as: :text %>
          <%= f.submit "Add tag", class: "btn btn-gradient" %>
        <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>